### ISSUE TITLE
Gallery subfolder sometimes isn't created

### ISSUE THREAD

**Issue by Aleph-00** [vasyaabr/booruextractor#1]
In Windows, gallery subfolders don't always get created. 
In the three occurrences I've seen, the gallery name contained characters that aren't usable for filenames (namely "/" , "|" and """ ). I'd suggest replacing those invalid characters with a _ . 
BTW I'd also ensure that the combined path + filename doesn't exceed 250 characters, perhaps by shortening the subfolder name... It isn't a filesystem limitation _per se_, but many applications don't correctly work if the total path length exceeds that limit.
Thanks for this utility!

**Comment by vasyaabr** [comment]
Thanks! I'll fix this in the nearest update!

**Comment by vasyaabr** [comment]
Update posted to addons gallery.
