### ISSUE TITLE
Issue downloading Highres pictures.

### ISSUE THREAD

**Issue by Khazran** [vasyaabr/booruextractor#2]
Hello, just created an account to post a little issue I have downloading Highres pictures.

The issue I have is sometime the pictures download with no problem and sometimes it don't. At first I believe it was caused by the large files (like 1mb and more) but it appears that it's not the case.

Secondo, I noticed that behond a certain resolution the pictures won't download. I tested it out a bit and found that:

1062x1500 download without issue.
and
1075x1504 won't download.

That was the 2 closest pictures that I could find in resolution.

And then I remembered that these sites (Gelbooru in my case) use a protection for "Large" pictures (mine is disabled) and just create a smaller thumbnail that you have to click a link to get the original size. Maybe that protection is blocking the direct download when opening Large pics. What bugs me is that even with the protection disabled I still have that issue...

I hope I helped a bit...
Great plugin and works great with small pictures!

**Comment by vasyaabr** [comment]
Must be fixed in last release (0.2.2), please check it.
