### ISSUE TITLE
Gelbooru download problem

### ISSUE THREAD

**Issue by Darkaeluz** [vasyaabr/booruextractor#4]
The add-on has troubles downloading from gelbooru, I've been opening a lot of images hoping for the add-on to save them only to discover later that it had only saved seven pictures and 6 gifs, and it doesnt download from danbooru.donmai.com

**Comment by vasyaabr** [comment]
Hi!
Can you provide a link to image, failed to download?

**Comment by Darkaeluz** [comment]
Practically almost any tag, family, blue_eyes, smiling, and some others more, can't give an exact link because there were a lot of images

**Comment by AkiraShirase** [comment]
there is problem with gelbooru url parsing, it has pictures without question mark in url, so parser can not substr file name correctly.

**Comment by Darkaeluz** [comment]
by the way, this problem got solved when I reinstalled the extension, I don't know if it is still valid for other users though

**Comment by vasyaabr** [comment]
@AkiraShirase is it still viable?

**Comment by vasyaabr** [comment]
Uploaded to mozilla, will be realeased in a few days.

**Comment by vasyaabr** [comment]
Released yesterday.
